[workspace]

[package]
name = "hello_web"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "hello_web"
path = "main.rs"

[dependencies]
open_gpui = { package = "open-gpui", path = "../../../gpui", default-features = false }
web-time = "1"

[dependencies.open_gpui_platform]
package = "open-gpui-platform"
path = "../../../gpui_platform"
features = ["web-multithreaded"]
