[package]
name = "open-gpui-windows"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
publish.workspace = true
description = "Windows platform backend for Open GPUI."

[lints]
workspace = true

[lib]
path = "src/gpui_windows.rs"

[features]
default = ["open_gpui/default"]
test-support = ["open_gpui/test-support"]
screen-capture = ["open_gpui/screen-capture", "scap"]

[dependencies]
open_gpui.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
accesskit.workspace = true
accesskit_windows.workspace = true
anyhow.workspace = true
open_gpui_collections.workspace = true
etagere = "0.2"
futures.workspace = true
image.workspace = true
itertools.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
raw-window-handle = "0.6"
smallvec.workspace = true
open_gpui_util.workspace = true
uuid.workspace = true
windows.workspace = true
windows-core.workspace = true
windows-numerics = "0.2"
windows-registry = "0.5"

[target.'cfg(target_os = "windows")'.dependencies.scap]
workspace = true
optional = true

[target.'cfg(target_os = "windows")'.build-dependencies]
windows-registry = "0.5"
