[package]
name = "open-gpui-collections"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
description = "Standard collection types used by Open GPUI."

[lints]
workspace = true

[lib]
path = "src/collections.rs"
doctest = false

[features]
test-support = []

[dependencies]
indexmap.workspace = true
rustc-hash.workspace = true
open_gpui_core_util.workspace = true
