[package]
name = "open-gpui-media"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
description = "macOS media API bindings used by Open GPUI."

[lints]
workspace = true

[lib]
path = "src/media.rs"
doctest = false

[dependencies]
anyhow.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation.workspace = true
ctor.workspace = true
objc2-core-foundation.workspace = true
objc2-core-video.workspace = true
objc.workspace = true

[build-dependencies]
bindgen = "0.72"
