[package]
name = "xtask"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
publish = false
description = "Workspace automation for Open GPUI."

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
toml = "0.8.23"

[lints]
workspace = true
