//! Component consumer samples for the foundation gallery.

#[path = "components/catalog.rs"]
pub mod catalog;
#[path = "components/conformance.rs"]
pub mod conformance;
mod render;
#[path = "components/runtime.rs"]
mod runtime;
#[path = "components/samples.rs"]
mod samples;

pub use catalog::{
    COMPONENT_CATALOG, COMPONENT_PAGE_JUMPS, ComponentCatalogEntry, ComponentCatalogStatus,
    ComponentFocusMode, ComponentPageJump, component_story_contract_for, component_story_contracts,
    component_story_contracts_for_focus, focused_section_for_catalog_entry, focused_section_for_id,
    official_sample_selector_pairs, state_contract_readout_pairs,
};
pub use conformance::{COMPONENT_CONFORMANCE_GATES, ComponentConformanceGate};
pub(crate) use render::{
    component_page_section_count, component_page_section_index, render_components_directory,
    render_components_page,
};
pub use runtime::{
    FormSampleRuntimeAction, FormSampleRuntimeCompletion, FormSampleRuntimeEvent,
    FormSampleRuntimeLog, ResourceSampleRuntimeEvent, ResourceSampleRuntimeLog,
    form_sample_runtime_log, resource_sample_runtime_log,
};
pub use runtime::{
    TableSampleCellEditChange, TableSampleColumnOrderChange, TableSampleColumnVisibilityChange,
    TableSampleExpansionToggle, TableSampleFacetedFilterChange, TableSampleGlobalFilterChange,
    TableSamplePredicateFilterChange, TableSampleRangeFilterChange, TableSampleRowActivation,
    TableSampleRuntimeLog, TableSampleSizingChange, TreeSampleMoveEvent, TreeSampleRuntimeLog,
    TreeSampleSelection, TreeSampleToggleEvent, VirtualizedListSampleActivation,
    VirtualizedListSampleNestedAction, VirtualizedListSampleRuntimeLog,
    current_table_sample_expansion, current_table_sample_sizing, record_table_cell_edit_change,
    record_table_column_order_change, record_table_column_visibility_change,
    record_table_expansion_request, record_table_faceted_filter_change,
    record_table_global_filter_change, record_table_predicate_filter_change,
    record_table_range_filter_change, record_table_row_activation, record_table_sizing_change,
    record_tree_move, record_tree_selection, record_tree_toggle,
    record_virtualized_list_activation, record_virtualized_list_nested_action,
    table_sample_state_with_runtime,
};
pub use samples::{
    AccordionSample, AvatarGroupSample, AvatarSample, BadgeSample, BreadcrumbSample, ButtonSample,
    CheckboxSample, CollapsibleSample, ComboboxSample, CommandSample, EmptyStateSample,
    FORM_DEVTOOLS_DOGFOOD_CANARIES, FieldSample, FieldTextareaSample, FormAdapterSample,
    FoundationComponentSamples, IconButtonSample, KbdSample, LabelSample, LinkSample,
    ListboxGroupSample, ListboxOptionSample, ListboxSample, NumberInputSample, ProgressSample,
    RadioGroupSample, RadioItemSample, ResourceAdapterSample, ResourceDevtoolsDogfoodSnapshots,
    ScrollAreaSample, SelectSample, SeparatorSample, SidebarItemSample, SidebarSample,
    SidebarSectionSample, SkeletonSample, SliderSample, SplitterPanelSample, SplitterSample,
    StatusCueSample, SwitchSample, TableSample, TableSampleStateSummary, TabsItemSample,
    TabsSample, TagSample, TextInputSample, TextareaSample, ToastStackSample, ToggleGroupSample,
    ToggleSample, ToolbarItemSample, ToolbarSample, TreeSample, TreeStateContractSample,
    VirtualizedListSample, VirtualizedListSampleRenderer, VirtualizedListSampleStateSummary,
    VirtualizedListStateContractSample, accordion_samples, avatar_group_samples, avatar_samples,
    badge_samples, breadcrumb_samples, button_samples, checkbox_samples, collapsible_samples,
    combobox_samples, command_samples, empty_state_samples, field_samples, field_textarea_samples,
    form_adapter_samples, form_devtools_dogfood_snapshot,
    form_devtools_validation_dogfood_snapshot, foundation_component_samples, icon_button_samples,
    kbd_samples, label_samples, link_samples, listbox_samples, number_input_samples,
    progress_samples, radio_group_samples, resource_adapter_samples,
    resource_devtools_dogfood_snapshots, scroll_area_samples, select_samples, separator_samples,
    sidebar_samples, skeleton_samples, slider_samples, splitter_samples, status_cue_samples,
    switch_samples, table_samples, tabs_samples, tag_samples, text_input_samples, textarea_samples,
    toast_stack_samples, toggle_group_samples, toggle_samples, toolbar_samples, tree_samples,
    tree_state_contract_samples, virtualized_list_samples, virtualized_list_state_contract_samples,
};

/// Page title.
pub const TITLE: &str = "Components";
/// Page summary.
pub const SUMMARY: &str = "First concrete component consumers built on the foundation crate.";
/// Foundation signals exercised by this page.
pub const SIGNALS: &[&str] = &[
    "open_gpui_ui_foundation_gallery::pages::components::COMPONENT_CONFORMANCE_GATES",
    "open_gpui_ui_foundation_gallery::pages::components::ComponentConformanceGate",
    "open_gpui_ui_foundation_gallery::pages::components::COMPONENT_CATALOG",
    "open_gpui_ui_foundation_gallery::pages::components::ComponentCatalogEntry",
    "open_gpui_ui_foundation_gallery::pages::components::ComponentCatalogStatus",
    "open_gpui_ui_foundation_gallery::pages::components::ComponentFocusMode",
    "open_gpui_ui_foundation_gallery::pages::components::component_story_contract_for",
    "open_gpui_ui_foundation_gallery::pages::components::component_story_contracts",
    "open_gpui_ui_foundation_gallery::pages::components::component_story_contracts_for_focus",
    "open_gpui_ui_foundation_gallery::pages::components::state_contract_readout_pairs",
    "open_gpui_ui_foundation_gallery::StoryContract",
    "open_gpui_ui_foundation_gallery::StoryProbeContract",
    "open_gpui_ui_foundation_gallery::StoryProbeOperation",
    "open_gpui_ui_components::Button",
    "open_gpui_ui_components::ButtonState",
    "open_gpui_ui_components::ButtonVariant",
    "open_gpui_ui_components::Badge",
    "open_gpui_ui_components::BadgeState",
    "open_gpui_ui_components::BadgeVariant",
    "open_gpui_ui_components::Accordion",
    "open_gpui_ui_components::AccordionState",
    "open_gpui_ui_components::Collapsible",
    "open_gpui_ui_components::CollapsibleState",
    "open_gpui_ui_components::Slider",
    "open_gpui_ui_components::SliderState",
    "open_gpui_ui_components::NumberInput",
    "open_gpui_ui_components::NumberInputState",
    "open_gpui_ui_components::ToggleGroup",
    "open_gpui_ui_components::ToggleGroupState",
    "open_gpui_ui_components::Link",
    "open_gpui_ui_components::LinkState",
    "open_gpui_ui_components::Breadcrumb",
    "open_gpui_ui_components::BreadcrumbState",
    "open_gpui_ui_components::Tag",
    "open_gpui_ui_components::TagState",
    "open_gpui_ui_components::ToastStack",
    "open_gpui_ui_components::ToastStackState",
    "open_gpui_ui_components::Separator",
    "open_gpui_ui_components::SeparatorState",
    "open_gpui_ui_components::Kbd",
    "open_gpui_ui_components::KbdState",
    "open_gpui_ui_components::Progress",
    "open_gpui_ui_components::ProgressState",
    "open_gpui_ui_components::ProgressVisualMode",
    "open_gpui_ui_components::Skeleton",
    "open_gpui_ui_components::SkeletonState",
    "open_gpui_ui_components::Avatar",
    "open_gpui_ui_components::AvatarGroup",
    "open_gpui_ui_components::AvatarGroupCount",
    "open_gpui_ui_components::AvatarGroupState",
    "open_gpui_ui_components::AvatarState",
    "open_gpui_ui_components::StatusCue",
    "open_gpui_ui_components::StatusCueState",
    "open_gpui_ui_components::EmptyState",
    "open_gpui_ui_components::EmptyStateState",
    "open_gpui_ui_components::FeedbackIntent",
    "open_gpui_ui_components::IconButton",
    "open_gpui_ui_components::IconButtonState",
    "open_gpui_ui_components::Switch",
    "open_gpui_ui_components::SwitchState",
    "open_gpui_ui_components::Checkbox",
    "open_gpui_ui_components::CheckboxState",
    "open_gpui_ui_components::RadioGroup",
    "open_gpui_ui_components::RadioGroupState",
    "open_gpui_ui_components::RadioItem",
    "open_gpui_ui_components::Toggle",
    "open_gpui_ui_components::ToggleState",
    "open_gpui_ui_components::ToggleVariant",
    "open_gpui_ui_components::Toolbar",
    "open_gpui_ui_components::toolbar::ToolbarItem",
    "open_gpui_ui_components::ToolbarState",
    "open_gpui_ui_components::ToolbarItemKind",
    "open_gpui_ui_components::Sidebar",
    "open_gpui_ui_components::SidebarState",
    "open_gpui_ui_components::SidebarSection",
    "open_gpui_ui_components::sidebar::SidebarItem",
    "open_gpui_ui_components::SidebarCollapseMode",
    "open_gpui_ui_components::Listbox",
    "open_gpui_ui_components::ListboxState",
    "open_gpui_ui_components::listbox::ListboxOption",
    "open_gpui_ui_components::ListboxGroup",
    "open_gpui_ui_components::Select",
    "open_gpui_ui_components::SelectState",
    "open_gpui_ui_components::SelectOpenMode",
    "open_gpui_ui_components::Combobox",
    "open_gpui_ui_components::ComboboxState",
    "open_gpui_ui_components::ComboboxOpenMode",
    "open_gpui_ui_components::Command",
    "open_gpui_ui_components::CommandState",
    "open_gpui_ui_components::CommandOpenMode",
    "open_gpui_ui_components::Label",
    "open_gpui_ui_components::LabelState",
    "open_gpui_ui_components::TextInput",
    "open_gpui_ui_components::TextInputDisplayMode",
    "open_gpui_ui_components::TextInputState",
    "open_gpui_ui_components::gpui_adapter::TextInputController",
    "open_gpui_ui_components::FormFieldConfig",
    "open_gpui_ui_components::FormFieldProjection",
    "open_gpui_ui_components::form_text_value",
    "open_gpui_ui_components::form_number_value",
    "open_gpui_ui_components::form_checkbox_value",
    "open_gpui_ui_components::form_select_value",
    "open_gpui_ui_components::Textarea",
    "open_gpui_ui_components::TextareaState",
    "open_gpui_ui_components::Field",
    "open_gpui_ui_components::FieldState",
    "open_gpui_ui_components::Tabs",
    "open_gpui_ui_components::TabsItem",
    "open_gpui_ui_components::TabsActivationMode",
    "open_gpui_ui_components::TabsState",
    "open_gpui_ui_components::ScrollArea",
    "open_gpui_ui_components::ScrollAreaState",
    "open_gpui_ui_components::ScrollAreaAxis",
    "open_gpui_ui_components::ScrollResetPolicy",
    "open_gpui_ui_components::Splitter",
    "open_gpui_ui_components::SplitterState",
    "open_gpui_ui_components::SplitterPanel",
    "open_gpui_ui_components::SplitterPanelDescriptor",
    "open_gpui_ui_components::Table",
    "open_gpui_ui_core::TableState",
    "open_gpui_ui_components::TableHeaderAction",
    "open_gpui_ui_core::TableAggregation",
    "open_gpui_ui_core::TableColumnFacets",
    "open_gpui_ui_core::TableFacetValueCount",
    "open_gpui_ui_core::TableFacetRange",
    "open_gpui_ui_core::TableColumnPinning",
    "open_gpui_ui_core::TableColumnRegion",
    "open_gpui_ui_core::TableColumnSizing",
    "open_gpui_ui_components::TableColumnSizingChange",
    "open_gpui_ui_components::TableColumnVisibility",
    "open_gpui_ui_components::TableColumnVisibilityAction",
    "open_gpui_ui_components::TableColumnVisibilityChange",
    "open_gpui_ui_components::TableColumnVisibilityItemState",
    "open_gpui_ui_core::TableColumnVisibilityOverrides",
    "open_gpui_ui_components::TableColumnVisibilityState",
    "open_gpui_ui_components::TableFacetedFilter",
    "open_gpui_ui_components::TableFacetedFilterChange",
    "open_gpui_ui_components::TableFacetedFilterOptionState",
    "open_gpui_ui_components::TableFacetedFilterState",
    "open_gpui_ui_components::TableGlobalFilter",
    "open_gpui_ui_components::TableGlobalFilterChange",
    "open_gpui_ui_components::TableGlobalFilterState",
    "open_gpui_ui_components::TablePredicateFilter",
    "open_gpui_ui_components::TablePredicateFilterChange",
    "open_gpui_ui_components::TablePredicateFilterOperator",
    "open_gpui_ui_components::TablePredicateFilterOperatorOptionState",
    "open_gpui_ui_components::TablePredicateFilterState",
    "open_gpui_ui_components::TableToolbar",
    "open_gpui_ui_components::TableToolbarState",
    "open_gpui_ui_components::TableRangeFilter",
    "open_gpui_ui_components::TableRangeFilterChange",
    "open_gpui_ui_components::TableRangeFilterState",
    "open_gpui_ui_components::ResourceAdapterLabels",
    "open_gpui_ui_components::ResourceCollectionProjection",
    "open_gpui_ui_components::ResourceMutationProjection",
    "open_gpui_ui_components::resource_query_key_label",
    "open_gpui_ui_core::TableColumnResizeMode",
    "open_gpui_ui_core::TableExpansionState",
    "open_gpui_ui_core::TableRowPinning",
    "open_gpui_ui_core::TableRowPinningPolicy",
    "open_gpui_ui_core::TableRowRegion",
    "open_gpui_ui_core::TableRowRegions",
    "open_gpui_ui_components::VirtualizedList",
    "open_gpui_ui_components::VirtualizedListItemDescriptor",
    "open_gpui_ui_components::VirtualizedListBehaviorSnapshot",
    "open_gpui_ui_core::VirtualizerState",
    "open_gpui_ui_components::Tree",
    "open_gpui_ui_components::TreeMetrics",
    "open_gpui_ui_components::TreeState",
    "open_gpui_ui_components::TreeItemDescriptor",
    "open_gpui_ui_components::TreeItemState",
    "open_gpui_ui_components::TreeSelection",
    "open_gpui_ui_components::TreeToggle",
    "open_gpui_ui_components::TreeFocusTarget",
    "open_gpui_ui_components::TreeKeyboardAction",
    "open_gpui_ui_components::tree_navigation_target",
    "open_gpui_ui_components::VirtualizedListState",
    "open_gpui_ui_components::VirtualizedListActivation",
    "open_gpui_ui_components::VirtualizedListMetrics",
    "open_gpui_ui_components::VirtualizedListScrollStrategy",
    "open_gpui_ui_components::VirtualizedListState::navigation_target",
    "open_gpui_ui_components::VirtualizedListState::scroll_target_for_key",
    "open_gpui_ui_components::VirtualizedListState::scroll_target_for_key_with_snapshot",
    "ThemeTokens",
    "Size",
    "Role::Button",
    "Role::Image",
    "Role::Label",
    "Role::Toolbar",
    "Role::Navigation",
    "Role::Section",
    "Role::ListBox",
    "Role::ListBoxOption",
    "Role::EditableComboBox",
    "Role::ProgressIndicator",
    "Role::Switch",
    "Role::CheckBox",
    "Role::RadioGroup",
    "Role::RadioButton",
    "Role::Label",
    "Role::TextInput",
    "Role::TabList",
    "Role::Tab",
    "Role::TabPanel",
    "Role::Tree",
    "Role::TreeItem",
];
