//! Public API inventory rows and method baselines.

use super::{
    CallbackApi, ComponentApiInventoryEntry, DefaultSeedApi, PublicSurfaceOwnerClass,
    component_contract_entry,
};

/// API inventory rows for official components and component recipes.
pub const COMPONENT_API_INVENTORY: &[ComponentApiInventoryEntry] = &[
    ComponentApiInventoryEntry {
        component: "Accordion",
        controlled_inputs: &["open_values"],
        default_seeds: &[DefaultSeedApi {
            builder: "default_open_values",
            runtime_value: "open_values",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &["mode", "collapsible"],
        callbacks: &[CallbackApi {
            name: "on_open_change",
            payload: "AccordionOpenChange",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Button",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &[],
        callbacks: &[CallbackApi {
            name: "on_click",
            payload: "ClickEvent",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Badge",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &[],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: Some("display-only primitive"),
    },
    ComponentApiInventoryEntry {
        component: "Collapsible",
        controlled_inputs: &["open"],
        default_seeds: &[DefaultSeedApi {
            builder: "default_open",
            runtime_value: "open",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &["content"],
        callbacks: &[CallbackApi {
            name: "on_open_change",
            payload: "bool",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Link",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["href", "external"],
        callbacks: &[CallbackApi {
            name: "on_activate",
            payload: "LinkActivation",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Breadcrumb",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["item", "disabled"],
        callbacks: &[CallbackApi {
            name: "on_activate",
            payload: "BreadcrumbActivation",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Tag",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["variant", "removable"],
        callbacks: &[CallbackApi {
            name: "on_remove",
            payload: "TagRemove",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "ToastStack",
        controlled_inputs: &["toasts"],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["max_visible", "toast"],
        callbacks: &[
            CallbackApi {
                name: "on_action",
                payload: "ToastAction",
            },
            CallbackApi {
                name: "on_dismiss",
                payload: "ToastDismiss",
            },
        ],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "IconButton",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &[],
        callbacks: &[CallbackApi {
            name: "on_click",
            payload: "ClickEvent",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Slider",
        controlled_inputs: &["value"],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["min", "max", "step"],
        callbacks: &[CallbackApi {
            name: "on_change",
            payload: "SliderChange",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "NumberInput",
        controlled_inputs: &["value"],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["min", "max", "step", "read_only", "invalid", "required"],
        callbacks: &[CallbackApi {
            name: "on_change",
            payload: "NumberInputChange",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Switch",
        controlled_inputs: &["checked"],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &[],
        callbacks: &[CallbackApi {
            name: "on_change",
            payload: "bool",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Checkbox",
        controlled_inputs: &["checked", "checked_state"],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &[],
        callbacks: &[CallbackApi {
            name: "on_toggle",
            payload: "Toggled",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "RadioGroup",
        controlled_inputs: &[],
        default_seeds: &[DefaultSeedApi {
            builder: "default_selected",
            runtime_value: "selected",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &["orientation"],
        callbacks: &[CallbackApi {
            name: "on_selection_change",
            payload: "RadioSelection",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Toggle",
        controlled_inputs: &["pressed"],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &[],
        callbacks: &[CallbackApi {
            name: "on_change",
            payload: "bool",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "ToggleGroup",
        controlled_inputs: &["selected_values"],
        default_seeds: &[
            DefaultSeedApi {
                builder: "default_selected_values",
                runtime_value: "selected_values",
            },
            DefaultSeedApi {
                builder: "default_focused",
                runtime_value: "focused",
            },
        ],
        legacy_seed_inputs: &[],
        policy_hints: &["orientation", "mode", "selection_required", "item"],
        callbacks: &[CallbackApi {
            name: "on_change",
            payload: "ToggleGroupSelectionChange",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Toolbar",
        controlled_inputs: &[],
        default_seeds: &[DefaultSeedApi {
            builder: "default_focused",
            runtime_value: "focused",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &["orientation"],
        callbacks: &[CallbackApi {
            name: "on_select",
            payload: "ToolbarSelection",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Sidebar",
        controlled_inputs: &["collapsed", "selected"],
        default_seeds: &[DefaultSeedApi {
            builder: "default_focused",
            runtime_value: "focused",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &["side", "variant", "collapse_mode"],
        callbacks: &[CallbackApi {
            name: "on_selection_change",
            payload: "SidebarSelection",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Tree",
        controlled_inputs: &[],
        default_seeds: &[
            DefaultSeedApi {
                builder: "default_selected",
                runtime_value: "selected",
            },
            DefaultSeedApi {
                builder: "default_focused",
                runtime_value: "focused",
            },
        ],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "virtualized",
            "viewport_item_count",
            "overscan_count",
            "draggable",
        ],
        callbacks: &[
            CallbackApi {
                name: "on_select",
                payload: "TreeSelection",
            },
            CallbackApi {
                name: "on_toggle",
                payload: "TreeToggle",
            },
            CallbackApi {
                name: "on_move",
                payload: "TreeMove",
            },
        ],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Listbox",
        controlled_inputs: &["selected", "active"],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["embedded", "typeahead_query"],
        callbacks: &[CallbackApi {
            name: "on_select",
            payload: "ListboxSelection",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Select",
        controlled_inputs: &["open", "selected", "active"],
        default_seeds: &[DefaultSeedApi {
            builder: "default_open",
            runtime_value: "open",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "placement",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
        ],
        callbacks: &[
            CallbackApi {
                name: "on_open_change",
                payload: "bool",
            },
            CallbackApi {
                name: "on_select",
                payload: "SelectSelection",
            },
        ],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Combobox",
        controlled_inputs: &["open", "selected", "active"],
        default_seeds: &[
            DefaultSeedApi {
                builder: "default_open",
                runtime_value: "open",
            },
            DefaultSeedApi {
                builder: "default_query",
                runtime_value: "query",
            },
        ],
        legacy_seed_inputs: &[],
        policy_hints: &["placement", "outside_press_policy"],
        callbacks: &[
            CallbackApi {
                name: "on_open_change",
                payload: "bool",
            },
            CallbackApi {
                name: "on_select",
                payload: "ComboboxSelection",
            },
        ],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Command",
        controlled_inputs: &[
            "open",
            "query",
            "selected",
            "selected_values",
            "active",
            "index_snapshot",
            "provider_refresh_projection",
        ],
        default_seeds: &[
            DefaultSeedApi {
                builder: "default_open",
                runtime_value: "open",
            },
            DefaultSeedApi {
                builder: "default_query",
                runtime_value: "query",
            },
        ],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "dialog",
            "dialog_enabled",
            "outside_press_policy",
            "escape_key_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "viewport_item_count",
            "row_height",
            "overscan",
        ],
        callbacks: &[
            CallbackApi {
                name: "on_open_change",
                payload: "bool",
            },
            CallbackApi {
                name: "on_query_change",
                payload: "String",
            },
            CallbackApi {
                name: "on_select",
                payload: "CommandSelection",
            },
            CallbackApi {
                name: "on_selected_values_change",
                payload: "CommandSelectionChange",
            },
        ],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Label",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["for_control"],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: Some("control-association primitive"),
    },
    ComponentApiInventoryEntry {
        component: "TextInput",
        controlled_inputs: &["value"],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["controller"],
        callbacks: &[CallbackApi {
            name: "on_change",
            payload: "String",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Textarea",
        controlled_inputs: &["value"],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["rows"],
        callbacks: &[CallbackApi {
            name: "on_change",
            payload: "String",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Field",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["control"],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: Some("composition wrapper"),
    },
    ComponentApiInventoryEntry {
        component: "Tabs",
        controlled_inputs: &[],
        default_seeds: &[DefaultSeedApi {
            builder: "default_selected",
            runtime_value: "selected",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &["orientation", "activation_mode"],
        callbacks: &[CallbackApi {
            name: "on_selection_change",
            payload: "TabsSelection",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "ScrollArea",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["axis", "reset_on_key", "preserve_scroll", "scroll_handle"],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Splitter",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["orientation", "panel"],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Table",
        controlled_inputs: &["state", "column_sizing", "column_order"],
        default_seeds: &[DefaultSeedApi {
            builder: "default_focused_row",
            runtime_value: "focused_row",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "virtualizer_snapshot",
            "expansion_mode",
            "filtering_mode",
            "sorting_mode",
            "faceting_mode",
            "facet_metadata",
            "pagination_mode",
            "pagination_totals",
            "row_pinning_policy",
            "enable_column_resizing",
            "column_resize_mode",
            "column_resize_direction",
            "column_order",
        ],
        callbacks: &[
            CallbackApi {
                name: "on_sort_requested",
                payload: "TableHeaderAction",
            },
            CallbackApi {
                name: "on_column_sizing_change",
                payload: "TableColumnSizingChange",
            },
            CallbackApi {
                name: "on_column_order_change",
                payload: "TableColumnOrderChange",
            },
            CallbackApi {
                name: "on_row_activate",
                payload: "TableRowActivation",
            },
            CallbackApi {
                name: "on_row_selection_change",
                payload: "TableRowSelectionChange",
            },
            CallbackApi {
                name: "on_row_expansion_request",
                payload: "TableRowExpansionToggle",
            },
            CallbackApi {
                name: "on_cell_edit_change",
                payload: "TableCellEditChange",
            },
        ],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "TableFacetedFilter",
        controlled_inputs: &["open", "query", "selected_values"],
        default_seeds: &[
            DefaultSeedApi {
                builder: "default_open",
                runtime_value: "open",
            },
            DefaultSeedApi {
                builder: "default_query",
                runtime_value: "query",
            },
        ],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "facets",
            "placeholder",
            "empty_label",
            "clear_label",
            "viewport_item_count",
            "placement_side",
            "placement_alignment",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
        ],
        callbacks: &[
            CallbackApi {
                name: "on_open_change",
                payload: "bool",
            },
            CallbackApi {
                name: "on_query_change",
                payload: "String",
            },
            CallbackApi {
                name: "on_change",
                payload: "TableFacetedFilterChange",
            },
        ],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "TableColumnVisibility",
        controlled_inputs: &["open", "visibility"],
        default_seeds: &[
            DefaultSeedApi {
                builder: "default_open",
                runtime_value: "open",
            },
            DefaultSeedApi {
                builder: "default_visibility",
                runtime_value: "visibility",
            },
        ],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "columns",
            "empty_label",
            "show_all_label",
            "reset_label",
            "disabled",
            "viewport_item_count",
            "placement_side",
            "placement_alignment",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
        ],
        callbacks: &[
            CallbackApi {
                name: "on_open_change",
                payload: "bool",
            },
            CallbackApi {
                name: "on_change",
                payload: "TableColumnVisibilityChange",
            },
        ],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "TableGlobalFilter",
        controlled_inputs: &["query"],
        default_seeds: &[DefaultSeedApi {
            builder: "default_query",
            runtime_value: "query",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &["placeholder", "clear_label", "disabled"],
        callbacks: &[CallbackApi {
            name: "on_change",
            payload: "TableGlobalFilterChange",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "TablePredicateFilter",
        controlled_inputs: &["operator", "value"],
        default_seeds: &[
            DefaultSeedApi {
                builder: "default_operator",
                runtime_value: "operator",
            },
            DefaultSeedApi {
                builder: "default_value",
                runtime_value: "value",
            },
        ],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "operator_option",
            "operators",
            "placeholder",
            "clear_label",
            "disabled",
            "tokens",
        ],
        callbacks: &[CallbackApi {
            name: "on_change",
            payload: "TablePredicateFilterChange",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "TableToolbar",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["control", "secondary_control", "summary", "tokens"],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: Some("slot container"),
    },
    ComponentApiInventoryEntry {
        component: "TableRangeFilter",
        controlled_inputs: &["open"],
        default_seeds: &[
            DefaultSeedApi {
                builder: "default_open",
                runtime_value: "open",
            },
            DefaultSeedApi {
                builder: "default_min_text",
                runtime_value: "min_text",
            },
            DefaultSeedApi {
                builder: "default_max_text",
                runtime_value: "max_text",
            },
        ],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "facets",
            "range",
            "clear_label",
            "placement_side",
            "placement_alignment",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
        ],
        callbacks: &[
            CallbackApi {
                name: "on_open_change",
                payload: "bool",
            },
            CallbackApi {
                name: "on_change",
                payload: "TableRangeFilterChange",
            },
        ],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "VirtualizedList",
        controlled_inputs: &[],
        default_seeds: &[
            DefaultSeedApi {
                builder: "default_active_index",
                runtime_value: "active_index",
            },
            DefaultSeedApi {
                builder: "default_selected_index",
                runtime_value: "selected_index",
            },
        ],
        legacy_seed_inputs: &[],
        policy_hints: &["viewport_item_count", "row_height", "overscan"],
        callbacks: &[CallbackApi {
            name: "on_activate",
            payload: "VirtualizedListActivation",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "StatusCue",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &[],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: Some("feedback readout"),
    },
    ComponentApiInventoryEntry {
        component: "EmptyState",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &[],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: Some("feedback readout"),
    },
    ComponentApiInventoryEntry {
        component: "Separator",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["orientation", "decorative"],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: Some("display-only primitive"),
    },
    ComponentApiInventoryEntry {
        component: "Kbd",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &[],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: Some("display-only primitive"),
    },
    ComponentApiInventoryEntry {
        component: "Progress",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["indeterminate"],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: Some("status readout"),
    },
    ComponentApiInventoryEntry {
        component: "Skeleton",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &[],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: Some("display-only loading placeholder"),
    },
    ComponentApiInventoryEntry {
        component: "Avatar",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["accessible_label"],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: Some("identity readout"),
    },
    ComponentApiInventoryEntry {
        component: "AvatarGroup",
        controlled_inputs: &[],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &["avatar", "max_visible"],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: Some("identity readout collection"),
    },
    ComponentApiInventoryEntry {
        component: "Tooltip",
        controlled_inputs: &["open"],
        default_seeds: &[],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "open_intent",
            "placement_side",
            "placement_alignment",
            "delay",
        ],
        callbacks: &[],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "HoverCard",
        controlled_inputs: &["open"],
        default_seeds: &[DefaultSeedApi {
            builder: "default_open",
            runtime_value: "open",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "open_intent",
            "placement_side",
            "placement_alignment",
            "delay",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
        ],
        callbacks: &[CallbackApi {
            name: "on_open_change",
            payload: "bool",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Popover",
        controlled_inputs: &["open"],
        default_seeds: &[DefaultSeedApi {
            builder: "default_open",
            runtime_value: "open",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "placement_side",
            "placement_alignment",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
        ],
        callbacks: &[CallbackApi {
            name: "on_open_change",
            payload: "bool",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Dialog",
        controlled_inputs: &["open"],
        default_seeds: &[DefaultSeedApi {
            builder: "default_open",
            runtime_value: "open",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "outside_press_policy",
            "escape_key_policy",
            "initial_focus_intent",
            "focus_restore_intent",
        ],
        callbacks: &[CallbackApi {
            name: "on_open_change",
            payload: "bool",
        }],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "AlertDialog",
        controlled_inputs: &["open"],
        default_seeds: &[DefaultSeedApi {
            builder: "default_open",
            runtime_value: "open",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "outside_press_policy",
            "escape_key_policy",
            "initial_focus_intent",
            "focus_restore_intent",
        ],
        callbacks: &[
            CallbackApi {
                name: "on_cancel",
                payload: "()",
            },
            CallbackApi {
                name: "on_action",
                payload: "()",
            },
            CallbackApi {
                name: "on_open_change",
                payload: "bool",
            },
        ],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Sheet",
        controlled_inputs: &["open"],
        default_seeds: &[DefaultSeedApi {
            builder: "default_open",
            runtime_value: "open",
        }],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "side",
            "modal_mode",
            "close_affordance",
            "outside_press_policy",
            "escape_key_policy",
            "initial_focus_intent",
            "focus_restore_intent",
        ],
        callbacks: &[
            CallbackApi {
                name: "on_close",
                payload: "()",
            },
            CallbackApi {
                name: "on_open_change",
                payload: "bool",
            },
        ],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "Menu",
        controlled_inputs: &["open"],
        default_seeds: &[
            DefaultSeedApi {
                builder: "default_open",
                runtime_value: "open",
            },
            DefaultSeedApi {
                builder: "default_focused_value",
                runtime_value: "focused_value",
            },
        ],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "placement",
            "outside_press_policy",
            "escape_key_policy",
            "initial_focus_intent",
            "focus_restore_intent",
        ],
        callbacks: &[
            CallbackApi {
                name: "on_open_change",
                payload: "bool",
            },
            CallbackApi {
                name: "on_select",
                payload: "MenuSelection",
            },
        ],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
    ComponentApiInventoryEntry {
        component: "ContextMenu",
        controlled_inputs: &["open"],
        default_seeds: &[
            DefaultSeedApi {
                builder: "default_open",
                runtime_value: "open",
            },
            DefaultSeedApi {
                builder: "default_focused_value",
                runtime_value: "focused_value",
            },
        ],
        legacy_seed_inputs: &[],
        policy_hints: &[
            "anchor_point",
            "outside_press_policy",
            "escape_key_policy",
            "initial_focus_intent",
            "focus_restore_intent",
        ],
        callbacks: &[
            CallbackApi {
                name: "on_open_change",
                payload: "bool",
            },
            CallbackApi {
                name: "on_select",
                payload: "MenuSelection",
            },
        ],
        renderer_neutral_state: true,
        no_interaction_note: None,
    },
];

/// Returns render/input builder methods that shape the component output.
pub fn component_render_inputs(component: &str) -> &'static [&'static str] {
    match component {
        "Button" => &["variant", "disabled", "selected", "tooltip"],
        "Badge" => &["variant"],
        "IconButton" => &["variant", "disabled", "selected", "tooltip"],
        "Switch" => &["label", "disabled"],
        "Checkbox" => &[
            "label",
            "aria_label",
            "indeterminate",
            "disabled",
            "required",
            "invalid",
        ],
        "RadioGroup" => &["label", "disabled", "required", "item"],
        "Toggle" => &["variant", "disabled"],
        "Toolbar" => &["disabled", "item", "items"],
        "Sidebar" => &["disabled", "section", "sections"],
        "Tree" => &[
            "item",
            "items",
            "virtualized",
            "viewport_item_count",
            "overscan_count",
            "draggable",
        ],
        "Listbox" => &[
            "option",
            "options",
            "group",
            "groups",
            "disabled",
            "empty_label",
        ],
        "Select" => &[
            "placeholder",
            "option",
            "options",
            "group",
            "groups",
            "disabled",
            "full_width",
        ],
        "Combobox" => &[
            "placeholder",
            "option",
            "options",
            "group",
            "groups",
            "disabled",
            "required",
            "empty_label",
        ],
        "Command" => &[
            "placeholder",
            "trigger_label",
            "item",
            "items",
            "group",
            "groups",
            "index_snapshot",
            "provider_refresh_projection",
            "disabled",
            "dialog_description",
            "loading",
            "idle",
            "empty_label",
        ],
        "Label" => &["required", "disabled"],
        "TextInput" => &[
            "placeholder",
            "display_mode",
            "disabled",
            "read_only",
            "invalid",
            "required",
        ],
        "Textarea" => &[
            "placeholder",
            "rows",
            "disabled",
            "read_only",
            "invalid",
            "required",
        ],
        "Field" => &[
            "help_text",
            "help",
            "error_text",
            "error",
            "required",
            "disabled",
            "invalid",
        ],
        "Tabs" => &["item"],
        "Splitter" => &["disabled", "panel"],
        "Table" => &[
            "label",
            "row_measure_mode",
            "overscan",
            "row_height",
            "header_height",
            "viewport_extent",
            "min_column_width",
            "expansion_mode",
            "enable_column_resizing",
            "column_resize_mode",
            "column_resize_direction",
            "content_fit_columns",
        ],
        "TableFacetedFilter" => &[
            "facets",
            "selected_values",
            "open",
            "default_open",
            "query",
            "default_query",
            "placeholder",
            "empty_label",
            "clear_label",
            "disabled",
            "viewport_item_count",
            "placement_side",
            "placement_alignment",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_open_change",
            "on_query_change",
            "on_change",
        ],
        "TableColumnVisibility" => &[
            "columns",
            "visibility",
            "default_visibility",
            "open",
            "default_open",
            "empty_label",
            "show_all_label",
            "reset_label",
            "disabled",
            "viewport_item_count",
            "placement_side",
            "placement_alignment",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_open_change",
            "on_change",
        ],
        "TablePredicateFilter" => &[
            "operator",
            "default_operator",
            "value",
            "default_value",
            "operator_option",
            "operators",
            "placeholder",
            "clear_label",
            "disabled",
            "tokens",
            "on_change",
        ],
        "TableToolbar" => &[
            "control",
            "controls",
            "secondary_control",
            "secondary_controls",
            "summary",
            "tokens",
        ],
        "VirtualizedList" => &["disabled", "viewport_item_count", "row_height", "overscan"],
        "StatusCue" => &["intent"],
        "EmptyState" => &["description", "intent"],
        "Separator" => &["orientation", "vertical", "decorative"],
        "Progress" => &["value", "indeterminate"],
        "Skeleton" => &["subtle"],
        "Avatar" => &["source", "fallback", "accessible_label"],
        "AvatarGroup" => &["avatars", "avatar", "max_visible"],
        "Tooltip" => &["text", "for_action", "for_action_in_context", "disabled"],
        "HoverCard" => &["disabled"],
        "Popover" => &["disabled"],
        "Dialog" => &["description", "disabled"],
        "AlertDialog" => &[
            "intent",
            "cancel_label",
            "disabled",
            "cancel_disabled",
            "action_disabled",
        ],
        "Sheet" => &["description", "disabled"],
        "Menu" => &[
            "trigger_icon",
            "item",
            "items",
            "disabled",
            "trigger_tooltip",
        ],
        "ContextMenu" => &["item", "items"],
        _ => &[],
    }
}

/// Returns the expected public builder/state method surface for a component.
pub fn component_public_methods(component: &str) -> &'static [&'static str] {
    match component {
        "Accordion" => &[
            "new",
            "mode",
            "collapsible",
            "open_values",
            "default_open_values",
            "item",
            "tokens",
            "on_open_change",
            "state",
        ],
        "Button" => &[
            "new", "variant", "disabled", "selected", "tokens", "on_click", "tooltip", "state",
        ],
        "Badge" => &["new", "variant", "tokens", "state"],
        "Collapsible" => &[
            "new",
            "open",
            "default_open",
            "disabled",
            "content",
            "tokens",
            "on_open_change",
            "state",
        ],
        "Link" => &[
            "new",
            "disabled",
            "external",
            "tokens",
            "on_activate",
            "state",
        ],
        "Breadcrumb" => &[
            "new",
            "disabled",
            "item",
            "items",
            "tokens",
            "on_activate",
            "state",
        ],
        "Tag" => &[
            "new",
            "variant",
            "removable",
            "disabled",
            "tokens",
            "on_remove",
            "state",
        ],
        "ToastStack" => &[
            "new",
            "toast",
            "toasts",
            "max_visible",
            "tokens",
            "on_action",
            "on_dismiss",
            "state",
        ],
        "IconButton" => &[
            "new",
            "variant",
            "disabled",
            "selected",
            "tokens",
            "on_click",
            "tooltip",
            "accessible_label",
            "state",
        ],
        "Slider" => &[
            "new",
            "value",
            "min",
            "max",
            "step",
            "disabled",
            "tokens",
            "on_change",
            "state",
        ],
        "NumberInput" => &[
            "new",
            "value",
            "min",
            "max",
            "step",
            "disabled",
            "read_only",
            "invalid",
            "required",
            "tokens",
            "on_change",
            "state",
        ],
        "Switch" => &[
            "new",
            "label",
            "checked",
            "disabled",
            "tokens",
            "on_change",
            "state",
        ],
        "Checkbox" => &[
            "new",
            "label",
            "aria_label",
            "checked",
            "indeterminate",
            "checked_state",
            "disabled",
            "required",
            "invalid",
            "tokens",
            "on_toggle",
            "state",
        ],
        "RadioGroup" => &[
            "new",
            "label",
            "orientation",
            "default_selected",
            "disabled",
            "required",
            "tokens",
            "item",
            "on_selection_change",
            "state",
        ],
        "Toggle" => &[
            "new",
            "variant",
            "pressed",
            "disabled",
            "tokens",
            "on_change",
            "state",
        ],
        "ToggleGroup" => &[
            "new",
            "orientation",
            "mode",
            "selected_values",
            "default_selected_values",
            "default_focused",
            "selection_required",
            "disabled",
            "tokens",
            "item",
            "items",
            "on_change",
            "state",
        ],
        "Toolbar" => &[
            "new",
            "orientation",
            "default_focused",
            "disabled",
            "tokens",
            "item",
            "items",
            "on_select",
            "state",
        ],
        "Sidebar" => &[
            "new",
            "side",
            "left",
            "right",
            "variant",
            "collapse_mode",
            "collapsed",
            "disabled",
            "selected",
            "default_focused",
            "tokens",
            "section",
            "sections",
            "on_selection_change",
            "state",
        ],
        "Tree" => &[
            "new",
            "item",
            "default_selected",
            "default_focused",
            "virtualized",
            "viewport_item_count",
            "overscan_count",
            "draggable",
            "on_select",
            "on_toggle",
            "on_move",
            "items",
            "state",
            "behavior_snapshot",
        ],
        "Listbox" => &[
            "new",
            "option",
            "options",
            "group",
            "groups",
            "disabled",
            "embedded",
            "selected",
            "active",
            "typeahead_query",
            "empty_label",
            "tokens",
            "on_select",
            "state",
        ],
        "Select" => &[
            "new",
            "placeholder",
            "option",
            "options",
            "group",
            "groups",
            "disabled",
            "full_width",
            "open",
            "default_open",
            "selected",
            "active",
            "placement",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_open_change",
            "on_select",
            "state",
        ],
        "Combobox" => &[
            "new",
            "placeholder",
            "option",
            "options",
            "group",
            "groups",
            "disabled",
            "required",
            "open",
            "default_open",
            "default_query",
            "selected",
            "active",
            "empty_label",
            "placement",
            "outside_press_policy",
            "tokens",
            "on_open_change",
            "on_select",
            "state",
        ],
        "Command" => &[
            "new",
            "placeholder",
            "trigger_label",
            "item",
            "items",
            "group",
            "groups",
            "index_snapshot",
            "provider_refresh_projection",
            "disabled",
            "open",
            "default_open",
            "dialog",
            "dialog_enabled",
            "dialog_description",
            "query",
            "default_query",
            "selection_mode",
            "multi_select",
            "selected",
            "selected_values",
            "active",
            "viewport_item_count",
            "row_height",
            "overscan",
            "loading",
            "idle",
            "empty_label",
            "outside_press_policy",
            "escape_key_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_open_change",
            "on_query_change",
            "on_select",
            "on_selected_values_change",
            "state",
            "behavior_snapshot",
            "behavior_snapshot_with_viewport",
        ],
        "Label" => &[
            "new",
            "for_control",
            "required",
            "disabled",
            "tokens",
            "state",
        ],
        "TextInput" => &[
            "new",
            "controller",
            "value",
            "on_change",
            "placeholder",
            "display_mode",
            "disabled",
            "read_only",
            "invalid",
            "required",
            "tokens",
            "state",
        ],
        "Textarea" => &[
            "new",
            "value",
            "on_change",
            "placeholder",
            "rows",
            "disabled",
            "read_only",
            "invalid",
            "required",
            "tokens",
            "state",
        ],
        "Field" => &[
            "new",
            "help_text",
            "help",
            "error_text",
            "error",
            "required",
            "disabled",
            "invalid",
            "tokens",
            "control",
            "state",
        ],
        "Tabs" => &[
            "new",
            "orientation",
            "activation_mode",
            "default_selected",
            "tokens",
            "item",
            "on_selection_change",
            "state",
        ],
        "ScrollArea" => &[
            "new",
            "axis",
            "vertical",
            "horizontal",
            "both",
            "scroll_handle",
            "reset_on_key",
            "preserve_scroll",
            "state",
        ],
        "Splitter" => &[
            "new",
            "orientation",
            "horizontal",
            "vertical",
            "disabled",
            "panel",
            "state",
        ],
        "Table" => &[
            "new",
            "label",
            "row_measure_mode",
            "overscan",
            "row_height",
            "header_height",
            "viewport_extent",
            "expansion_mode",
            "min_column_width",
            "virtualizer_snapshot",
            "default_focused_row",
            "on_sort_requested",
            "on_column_order_change",
            "enable_column_resizing",
            "column_resize_mode",
            "column_resize_direction",
            "on_column_sizing_change",
            "on_row_selection_change",
            "on_row_activate",
            "on_row_expansion_request",
            "on_cell_edit_change",
            "state",
            "behavior_snapshot",
        ],
        "TableFacetedFilter" => &[
            "new",
            "facets",
            "selected_values",
            "open",
            "default_open",
            "query",
            "default_query",
            "placeholder",
            "empty_label",
            "clear_label",
            "disabled",
            "viewport_item_count",
            "placement_side",
            "placement_alignment",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_open_change",
            "on_query_change",
            "on_change",
            "state",
        ],
        "TableColumnVisibility" => &[
            "new",
            "columns",
            "visibility",
            "default_visibility",
            "open",
            "default_open",
            "empty_label",
            "show_all_label",
            "reset_label",
            "disabled",
            "viewport_item_count",
            "placement_side",
            "placement_alignment",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_open_change",
            "on_change",
            "state",
        ],
        "TableGlobalFilter" => &[
            "new",
            "query",
            "default_query",
            "placeholder",
            "clear_label",
            "disabled",
            "tokens",
            "on_change",
            "state",
        ],
        "TablePredicateFilter" => &[
            "new",
            "operator",
            "default_operator",
            "value",
            "default_value",
            "operator_option",
            "operators",
            "placeholder",
            "clear_label",
            "disabled",
            "tokens",
            "on_change",
            "state",
        ],
        "TableToolbar" => &[
            "new",
            "control",
            "controls",
            "secondary_control",
            "secondary_controls",
            "summary",
            "tokens",
            "state",
        ],
        "TableRangeFilter" => &[
            "new",
            "facets",
            "range",
            "default_min_text",
            "default_max_text",
            "open",
            "default_open",
            "clear_label",
            "disabled",
            "placement_side",
            "placement_alignment",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_open_change",
            "on_change",
            "state",
        ],
        "VirtualizedList" => &[
            "new",
            "from_shared_items",
            "disabled",
            "default_active_index",
            "default_selected_index",
            "viewport_item_count",
            "row_height",
            "overscan",
            "on_activate",
            "state",
            "behavior_snapshot",
            "behavior_snapshot_with_viewport",
        ],
        "StatusCue" => &["new", "intent", "tokens", "state"],
        "EmptyState" => &["new", "description", "intent", "tokens", "state"],
        "Separator" => &[
            "new",
            "orientation",
            "vertical",
            "decorative",
            "tokens",
            "state",
        ],
        "Kbd" => &["new", "tokens", "state"],
        "Progress" => &["new", "value", "indeterminate", "tokens", "state"],
        "Skeleton" => &["new", "subtle", "tokens", "state"],
        "Avatar" => &[
            "new",
            "source",
            "fallback",
            "accessible_label",
            "tokens",
            "state",
        ],
        "AvatarGroup" => &["new", "avatar", "avatars", "max_visible", "tokens", "state"],
        "Tooltip" => &[
            "new",
            "element",
            "text",
            "for_action",
            "for_action_in_context",
            "disabled",
            "open",
            "open_intent",
            "placement_side",
            "placement_alignment",
            "delay",
            "tokens",
            "state",
        ],
        "HoverCard" => &[
            "new",
            "element",
            "disabled",
            "open",
            "default_open",
            "open_intent",
            "placement_side",
            "placement_alignment",
            "delay",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_open_change",
            "state",
        ],
        "Popover" => &[
            "new",
            "element",
            "disabled",
            "open",
            "default_open",
            "placement_side",
            "placement_alignment",
            "outside_press_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_open_change",
            "state",
        ],
        "Dialog" => &[
            "new",
            "element",
            "description",
            "disabled",
            "open",
            "default_open",
            "outside_press_policy",
            "escape_key_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_open_change",
            "state",
        ],
        "AlertDialog" => &[
            "new",
            "intent",
            "cancel_label",
            "disabled",
            "cancel_disabled",
            "action_disabled",
            "open",
            "default_open",
            "outside_press_policy",
            "escape_key_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_cancel",
            "on_action",
            "on_open_change",
            "state",
        ],
        "Sheet" => &[
            "new",
            "element",
            "description",
            "disabled",
            "open",
            "default_open",
            "side",
            "modal_mode",
            "close_affordance",
            "outside_press_policy",
            "escape_key_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_close",
            "on_open_change",
            "state",
        ],
        "Menu" => &[
            "new",
            "trigger_icon",
            "item",
            "items",
            "disabled",
            "open",
            "default_open",
            "default_focused_value",
            "placement",
            "outside_press_policy",
            "escape_key_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_open_change",
            "on_select",
            "trigger_tooltip",
            "state",
        ],
        "ContextMenu" => &[
            "new",
            "item",
            "items",
            "open",
            "default_open",
            "anchor_point",
            "default_focused_value",
            "outside_press_policy",
            "escape_key_policy",
            "initial_focus_intent",
            "focus_restore_intent",
            "tokens",
            "on_open_change",
            "on_select",
            "state",
        ],
        _ => panic!("missing public method baseline for `{component}`"),
    }
}

/// Returns the public surface owner class for an inventory component row.
pub fn public_owner_for_component_inventory(component: &str) -> PublicSurfaceOwnerClass {
    component_contract_entry(component)
        .map(|entry| entry.owner)
        .unwrap_or_else(|| panic!("missing public owner mapping for `{component}`"))
}
