//! Typed projections joining narrow product and public-export owners.

use super::{
    COMPONENT_CONTRACT_ROWS, ComponentContractEntry, ComponentContractMetadata, PublicApiExport,
};

/// Returns the canonical product row for an official component contract id.
pub const fn component_contract_entry(id: &str) -> Option<&'static ComponentContractEntry> {
    let mut index = 0;
    while index < COMPONENT_CONTRACT_ROWS.len() {
        let entry = &COMPONENT_CONTRACT_ROWS[index];
        if token_eq(entry.id().as_str(), id) {
            return Some(entry);
        }
        index += 1;
    }

    None
}

/// Returns shared product metadata for an official component contract id.
pub const fn component_contract_metadata(id: &str) -> Option<ComponentContractMetadata> {
    match component_contract_entry(id) {
        Some(entry) => Some(entry.metadata()),
        None => None,
    }
}

/// Returns exports generated by the common crate-root/module/prelude declaration.
pub fn common_public_exports() -> impl Iterator<Item = &'static PublicApiExport> {
    crate::public_api::common::COMMON_PUBLIC_EXPORTS.iter()
}

/// Returns exports generated by the complete crate-root declaration.
pub fn default_public_exports() -> impl Iterator<Item = &'static PublicApiExport> {
    common_public_exports().chain(crate::public_api::default::EXTENDED_PUBLIC_EXPORTS)
}

/// Returns diagnostic exports available only through explicit owner modules.
pub fn diagnostic_public_exports() -> impl Iterator<Item = &'static PublicApiExport> {
    crate::table::TABLE_DIAGNOSTIC_EXPORTS.iter()
}

const fn token_eq(left: &str, right: &str) -> bool {
    let left = left.as_bytes();
    let right = right.as_bytes();
    if left.len() != right.len() {
        return false;
    }

    let mut index = 0;
    while index < left.len() {
        if left[index] != right[index] {
            return false;
        }
        index += 1;
    }

    true
}
