[package]
name = "open-gpui-shared-string"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
publish.workspace = true
description = "Shared string type used by Open GPUI."

[lib]
path = "gpui_shared_string.rs"

[dependencies]
schemars.workspace = true
serde.workspace = true
smol_str = "0.3.6"

[lints]
workspace = true
