//! Canonical component contract catalog rows.

use super::super::{
    ComponentContractEntry, PublicSurfaceOwnerClass, SurfaceDocsStatus, SurfaceGalleryStatus,
};

/// Product-level metadata rows for official components and adjacent public surfaces.
pub const COMPONENT_CONTRACT_ROWS: &[ComponentContractEntry] = &[
    ComponentContractEntry {
        name: "Accordion",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("disclosure"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Accordion"),
        default_export: true,
        source_inputs: &["accordion.rs"],
        source_home: "accordion.rs",
    },
    ComponentContractEntry {
        name: "Button",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("action"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Button"),
        default_export: true,
        source_inputs: &["button.rs"],
        source_home: "button.rs",
    },
    ComponentContractEntry {
        name: "Badge",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("display"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Badge"),
        default_export: true,
        source_inputs: &["badge.rs"],
        source_home: "badge.rs",
    },
    ComponentContractEntry {
        name: "Collapsible",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("disclosure"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Collapsible"),
        default_export: true,
        source_inputs: &["collapsible.rs"],
        source_home: "collapsible.rs",
    },
    ComponentContractEntry {
        name: "Link",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("navigation"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Link"),
        default_export: true,
        source_inputs: &["link.rs"],
        source_home: "link.rs",
    },
    ComponentContractEntry {
        name: "Breadcrumb",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("navigation"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Breadcrumb"),
        default_export: true,
        source_inputs: &["breadcrumb.rs"],
        source_home: "breadcrumb.rs",
    },
    ComponentContractEntry {
        name: "Tag",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("display"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Tag"),
        default_export: true,
        source_inputs: &["tag.rs"],
        source_home: "tag.rs",
    },
    ComponentContractEntry {
        name: "ToastStack",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("feedback"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("ToastStack"),
        default_export: true,
        source_inputs: &["toast.rs"],
        source_home: "toast.rs",
    },
    ComponentContractEntry {
        name: "IconButton",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("action"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("IconButton"),
        default_export: true,
        source_inputs: &["icon_button.rs"],
        source_home: "icon_button.rs",
    },
    ComponentContractEntry {
        name: "Slider",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("form"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Slider"),
        default_export: true,
        source_inputs: &["slider.rs"],
        source_home: "slider.rs",
    },
    ComponentContractEntry {
        name: "NumberInput",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("form"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("NumberInput"),
        default_export: true,
        source_inputs: &["number_input.rs"],
        source_home: "number_input.rs",
    },
    ComponentContractEntry {
        name: "Switch",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("form"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Switch"),
        default_export: true,
        source_inputs: &["switch.rs"],
        source_home: "switch.rs",
    },
    ComponentContractEntry {
        name: "Checkbox",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("form"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Checkbox"),
        default_export: true,
        source_inputs: &["checkbox.rs"],
        source_home: "checkbox.rs",
    },
    ComponentContractEntry {
        name: "RadioGroup",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("choice"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("RadioGroup"),
        default_export: true,
        source_inputs: &["radio.rs"],
        source_home: "radio.rs",
    },
    ComponentContractEntry {
        name: "Toggle",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("action"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Toggle"),
        default_export: true,
        source_inputs: &["toggle.rs"],
        source_home: "toggle.rs",
    },
    ComponentContractEntry {
        name: "ToggleGroup",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("action"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("ToggleGroup"),
        default_export: true,
        source_inputs: &["toggle_group.rs"],
        source_home: "toggle_group.rs",
    },
    ComponentContractEntry {
        name: "Toolbar",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("shell"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Toolbar"),
        default_export: true,
        source_inputs: &["toolbar.rs"],
        source_home: "toolbar.rs",
    },
    ComponentContractEntry {
        name: "Sidebar",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("shell"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Sidebar"),
        default_export: true,
        source_inputs: &["sidebar.rs"],
        source_home: "sidebar.rs",
    },
    ComponentContractEntry {
        name: "Tree",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("hierarchy"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Tree"),
        default_export: true,
        source_inputs: &[
            "tree/mod.rs",
            "tree/descriptor.rs",
            "tree/model.rs",
            "tree/runtime.rs",
            "tree/style.rs",
            "tree/movement.rs",
            "tree/render_plan.rs",
        ],
        source_home: "tree/mod.rs",
    },
    ComponentContractEntry {
        name: "Listbox",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("choice"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Listbox"),
        default_export: true,
        source_inputs: &["listbox.rs"],
        source_home: "listbox.rs",
    },
    ComponentContractEntry {
        name: "Select",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("choice"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Select"),
        default_export: true,
        source_inputs: &[
            "select/mod.rs",
            "select/model.rs",
            "select/render_plan.rs",
            "select/runtime.rs",
            "select/style.rs",
        ],
        source_home: "select/mod.rs",
    },
    ComponentContractEntry {
        name: "SelectStateRequest",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("choice"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("SelectStateRequest"),
        default_export: true,
        source_inputs: &["select/model.rs"],
        source_home: "select/model.rs",
    },
    ComponentContractEntry {
        name: "Combobox",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("choice-search"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Combobox"),
        default_export: true,
        source_inputs: &[
            "combobox/mod.rs",
            "combobox/descriptor.rs",
            "combobox/model.rs",
            "combobox/render_plan.rs",
            "combobox/runtime.rs",
            "combobox/style.rs",
        ],
        source_home: "combobox/mod.rs",
    },
    ComponentContractEntry {
        name: "ComboboxStateRequest",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("choice-search"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ComboboxStateRequest"),
        default_export: true,
        source_inputs: &["combobox/model.rs"],
        source_home: "combobox/model.rs",
    },
    ComponentContractEntry {
        name: "Command",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("choice-search"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Command"),
        default_export: true,
        source_inputs: &[
            "command/mod.rs",
            "command/descriptor.rs",
            "command/model.rs",
            "command/render_plan.rs",
            "command/runtime.rs",
            "command/style.rs",
        ],
        source_home: "command/mod.rs",
    },
    ComponentContractEntry {
        name: "CommandStateRequest",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("choice-search"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("CommandStateRequest"),
        default_export: true,
        source_inputs: &["command/model.rs"],
        source_home: "command/model.rs",
    },
    ComponentContractEntry {
        name: "CommandStateDataSource",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("choice-search"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("CommandStateDataSource"),
        default_export: true,
        source_inputs: &["command/model.rs"],
        source_home: "command/model.rs",
    },
    ComponentContractEntry {
        name: "Label",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("form"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Label"),
        default_export: true,
        source_inputs: &["label.rs"],
        source_home: "label.rs",
    },
    ComponentContractEntry {
        name: "TextInput",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("form"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("TextInput"),
        default_export: true,
        source_inputs: &["text_input.rs"],
        source_home: "text_input.rs",
    },
    ComponentContractEntry {
        name: "Textarea",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("form"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Textarea"),
        default_export: true,
        source_inputs: &["textarea.rs"],
        source_home: "textarea.rs",
    },
    ComponentContractEntry {
        name: "Field",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("form"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Field"),
        default_export: true,
        source_inputs: &["field.rs"],
        source_home: "field.rs",
    },
    ComponentContractEntry {
        name: "Tabs",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("navigation"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Tabs"),
        default_export: true,
        source_inputs: &["tabs.rs"],
        source_home: "tabs.rs",
    },
    ComponentContractEntry {
        name: "ScrollArea",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("layout"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("ScrollArea"),
        default_export: true,
        source_inputs: &["scroll_area.rs"],
        source_home: "scroll_area.rs",
    },
    ComponentContractEntry {
        name: "Splitter",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("layout"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Splitter"),
        default_export: true,
        source_inputs: &["splitter.rs"],
        source_home: "splitter.rs",
    },
    ComponentContractEntry {
        name: "Table",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("data"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Table"),
        default_export: true,
        source_inputs: &["table/mod.rs", "table/resolve.rs"],
        source_home: "table/mod.rs",
    },
    ComponentContractEntry {
        name: "TableFacetedFilter",
        owner: PublicSurfaceOwnerClass::OfficialComponentRecipe,
        family: Some("data"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("TableFacetedFilter"),
        default_export: true,
        source_inputs: &["table/faceted_filter"],
        source_home: "table/faceted_filter",
    },
    ComponentContractEntry {
        name: "TableColumnVisibility",
        owner: PublicSurfaceOwnerClass::OfficialComponentRecipe,
        family: Some("data"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("TableColumnVisibility"),
        default_export: true,
        source_inputs: &["table/column_visibility"],
        source_home: "table/column_visibility",
    },
    ComponentContractEntry {
        name: "TableGlobalFilter",
        owner: PublicSurfaceOwnerClass::OfficialComponentRecipe,
        family: Some("data"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("TableGlobalFilter"),
        default_export: true,
        source_inputs: &["table/global_filter"],
        source_home: "table/global_filter",
    },
    ComponentContractEntry {
        name: "TablePredicateFilter",
        owner: PublicSurfaceOwnerClass::OfficialComponentRecipe,
        family: Some("data"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("TablePredicateFilter"),
        default_export: true,
        source_inputs: &["table/predicate_filter"],
        source_home: "table/predicate_filter",
    },
    ComponentContractEntry {
        name: "TableToolbar",
        owner: PublicSurfaceOwnerClass::OfficialComponentRecipe,
        family: Some("data"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("TableToolbar"),
        default_export: true,
        source_inputs: &["table/toolbar.rs"],
        source_home: "table/toolbar.rs",
    },
    ComponentContractEntry {
        name: "TableRangeFilter",
        owner: PublicSurfaceOwnerClass::OfficialComponentRecipe,
        family: Some("data"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("TableRangeFilter"),
        default_export: true,
        source_inputs: &["table/range_filter"],
        source_home: "table/range_filter",
    },
    ComponentContractEntry {
        name: "VirtualizedList",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("data"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("VirtualizedList"),
        default_export: true,
        source_inputs: &["virtualized_list.rs"],
        source_home: "virtualized_list.rs",
    },
    ComponentContractEntry {
        name: "StatusCue",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("feedback"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("StatusCue"),
        default_export: true,
        source_inputs: &["feedback.rs"],
        source_home: "feedback.rs",
    },
    ComponentContractEntry {
        name: "EmptyState",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("feedback"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("EmptyState"),
        default_export: true,
        source_inputs: &["feedback.rs"],
        source_home: "feedback.rs",
    },
    ComponentContractEntry {
        name: "Separator",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("layout"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Separator"),
        default_export: true,
        source_inputs: &["separator.rs"],
        source_home: "separator.rs",
    },
    ComponentContractEntry {
        name: "Kbd",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("display"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Kbd"),
        default_export: true,
        source_inputs: &["kbd.rs"],
        source_home: "kbd.rs",
    },
    ComponentContractEntry {
        name: "Progress",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("status"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Progress"),
        default_export: true,
        source_inputs: &["progress.rs"],
        source_home: "progress.rs",
    },
    ComponentContractEntry {
        name: "Skeleton",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("status"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Skeleton"),
        default_export: true,
        source_inputs: &["skeleton.rs"],
        source_home: "skeleton.rs",
    },
    ComponentContractEntry {
        name: "Avatar",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("identity"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Avatar"),
        default_export: true,
        source_inputs: &["avatar.rs"],
        source_home: "avatar.rs",
    },
    ComponentContractEntry {
        name: "AvatarGroup",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("identity"),
        gallery_status: SurfaceGalleryStatus::OfficialComponent,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("AvatarGroup"),
        default_export: true,
        source_inputs: &["avatar.rs"],
        source_home: "avatar.rs",
    },
    ComponentContractEntry {
        name: "Tooltip",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("overlay"),
        gallery_status: SurfaceGalleryStatus::OfficialOverlay,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Tooltip"),
        default_export: true,
        source_inputs: &["tooltip.rs"],
        source_home: "tooltip.rs",
    },
    ComponentContractEntry {
        name: "HoverCard",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("overlay"),
        gallery_status: SurfaceGalleryStatus::OfficialOverlay,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("HoverCard"),
        default_export: true,
        source_inputs: &["hover_card.rs"],
        source_home: "hover_card.rs",
    },
    ComponentContractEntry {
        name: "Popover",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("overlay"),
        gallery_status: SurfaceGalleryStatus::OfficialOverlay,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Popover"),
        default_export: true,
        source_inputs: &["popover.rs"],
        source_home: "popover.rs",
    },
    ComponentContractEntry {
        name: "Dialog",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("overlay"),
        gallery_status: SurfaceGalleryStatus::OfficialOverlay,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Dialog"),
        default_export: true,
        source_inputs: &["dialog.rs"],
        source_home: "dialog.rs",
    },
    ComponentContractEntry {
        name: "AlertDialog",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("overlay"),
        gallery_status: SurfaceGalleryStatus::OfficialOverlay,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("AlertDialog"),
        default_export: true,
        source_inputs: &["alert_dialog.rs"],
        source_home: "alert_dialog.rs",
    },
    ComponentContractEntry {
        name: "Sheet",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("overlay"),
        gallery_status: SurfaceGalleryStatus::OfficialOverlay,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Sheet"),
        default_export: true,
        source_inputs: &["sheet.rs"],
        source_home: "sheet.rs",
    },
    ComponentContractEntry {
        name: "Menu",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("overlay"),
        gallery_status: SurfaceGalleryStatus::OfficialOverlay,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("Menu"),
        default_export: true,
        source_inputs: &[
            "menu/mod.rs",
            "menu/descriptor.rs",
            "menu/model.rs",
            "menu/render_plan.rs",
            "menu/runtime.rs",
            "menu/style.rs",
        ],
        source_home: "menu/mod.rs",
    },
    ComponentContractEntry {
        name: "ContextMenu",
        owner: PublicSurfaceOwnerClass::OfficialComponent,
        family: Some("overlay"),
        gallery_status: SurfaceGalleryStatus::OfficialOverlay,
        docs_status: SurfaceDocsStatus::ComponentCatalog,
        docs_token: Some("ContextMenu"),
        default_export: true,
        source_inputs: &[
            "context_menu/mod.rs",
            "context_menu/model.rs",
            "menu/mod.rs",
            "menu/descriptor.rs",
            "menu/model.rs",
            "menu/runtime.rs",
            "menu/style.rs",
        ],
        source_home: "context_menu/mod.rs",
    },
    ComponentContractEntry {
        name: "TreeState",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("hierarchy"),
        gallery_status: SurfaceGalleryStatus::StateContract,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("TreeState"),
        default_export: true,
        source_inputs: &[
            "tree/model.rs",
            "tree/descriptor.rs",
            "tree/style.rs",
            "tree/movement.rs",
        ],
        source_home: "tree/model.rs",
    },
    ComponentContractEntry {
        name: "VirtualizedListState",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("data"),
        gallery_status: SurfaceGalleryStatus::StateContract,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("VirtualizedListState"),
        default_export: true,
        source_inputs: &["virtualized_list.rs"],
        source_home: "virtualized_list.rs",
    },
    ComponentContractEntry {
        name: "ComponentA11yContract",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("accessibility"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ComponentA11yContract"),
        default_export: true,
        source_inputs: &["a11y.rs"],
        source_home: "a11y.rs",
    },
    ComponentContractEntry {
        name: "A11yLabelSource",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("accessibility"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("A11yLabelSource"),
        default_export: true,
        source_inputs: &["a11y.rs"],
        source_home: "a11y.rs",
    },
    ComponentContractEntry {
        name: "A11yDescriptionSource",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("accessibility"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("A11yDescriptionSource"),
        default_export: true,
        source_inputs: &["a11y.rs"],
        source_home: "a11y.rs",
    },
    ComponentContractEntry {
        name: "A11yValueMetadata",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("accessibility"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("A11yValueMetadata"),
        default_export: true,
        source_inputs: &["a11y.rs"],
        source_home: "a11y.rs",
    },
    ComponentContractEntry {
        name: "A11yValueKind",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("accessibility"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("A11yValueKind"),
        default_export: true,
        source_inputs: &["a11y.rs"],
        source_home: "a11y.rs",
    },
    ComponentContractEntry {
        name: "A11yContractError",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("accessibility"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("A11yContractError"),
        default_export: true,
        source_inputs: &["a11y.rs"],
        source_home: "a11y.rs",
    },
    ComponentContractEntry {
        name: "A11yContractViolation",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("accessibility"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("A11yContractViolation"),
        default_export: true,
        source_inputs: &["a11y.rs"],
        source_home: "a11y.rs",
    },
    ComponentContractEntry {
        name: "ThemeColor",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ThemeColor"),
        default_export: true,
        source_inputs: &["theme/snapshot.rs"],
        source_home: "theme/snapshot.rs",
    },
    ComponentContractEntry {
        name: "ThemeMode",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ThemeMode"),
        default_export: true,
        source_inputs: &["theme/snapshot.rs"],
        source_home: "theme/snapshot.rs",
    },
    ComponentContractEntry {
        name: "ThemeSnapshot",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ThemeSnapshot"),
        default_export: true,
        source_inputs: &["theme/snapshot.rs"],
        source_home: "theme/snapshot.rs",
    },
    ComponentContractEntry {
        name: "ThemeDefinition",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ThemeDefinition"),
        default_export: false,
        source_inputs: &["theme/registry.rs"],
        source_home: "theme/registry.rs",
    },
    ComponentContractEntry {
        name: "ThemeRegistry",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ThemeRegistry"),
        default_export: false,
        source_inputs: &["theme/registry.rs"],
        source_home: "theme/registry.rs",
    },
    ComponentContractEntry {
        name: "ThemeRegistryEntry",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ThemeRegistryEntry"),
        default_export: false,
        source_inputs: &["theme/registry.rs"],
        source_home: "theme/registry.rs",
    },
    ComponentContractEntry {
        name: "ThemeRegistrationDiagnostics",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ThemeRegistrationDiagnostics"),
        default_export: false,
        source_inputs: &["theme/registry.rs"],
        source_home: "theme/registry.rs",
    },
    ComponentContractEntry {
        name: "ThemeValidationError",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ThemeValidationError"),
        default_export: false,
        source_inputs: &["theme/registry.rs"],
        source_home: "theme/registry.rs",
    },
    ComponentContractEntry {
        name: "ThemeResolver",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ThemeResolver"),
        default_export: true,
        source_inputs: &["theme/resolver.rs"],
        source_home: "theme/resolver.rs",
    },
    ComponentContractEntry {
        name: "THEME_JSON_SCHEMA_VERSION",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("THEME_JSON_SCHEMA_VERSION"),
        default_export: false,
        source_inputs: &["theme/schema.rs"],
        source_home: "theme/schema.rs",
    },
    ComponentContractEntry {
        name: "ThemeFileField",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ThemeFileField"),
        default_export: false,
        source_inputs: &["theme/schema.rs"],
        source_home: "theme/schema.rs",
    },
    ComponentContractEntry {
        name: "ThemeLoadError",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ThemeLoadError"),
        default_export: false,
        source_inputs: &["theme/schema.rs"],
        source_home: "theme/schema.rs",
    },
    ComponentContractEntry {
        name: "theme_json_schema",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("theme_json_schema"),
        default_export: false,
        source_inputs: &["theme/schema.rs"],
        source_home: "theme/schema.rs",
    },
    ComponentContractEntry {
        name: "theme_definition_from_json_str",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("theme_definition_from_json_str"),
        default_export: false,
        source_inputs: &["theme/schema.rs"],
        source_home: "theme/schema.rs",
    },
    ComponentContractEntry {
        name: "theme_definition_from_json_file",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("theme_definition_from_json_file"),
        default_export: false,
        source_inputs: &["theme/schema.rs"],
        source_home: "theme/schema.rs",
    },
    ComponentContractEntry {
        name: "register_theme_json_str",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("register_theme_json_str"),
        default_export: false,
        source_inputs: &["theme/schema.rs"],
        source_home: "theme/schema.rs",
    },
    ComponentContractEntry {
        name: "register_theme_json_file",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: Some("theme"),
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("register_theme_json_file"),
        default_export: false,
        source_inputs: &["theme/schema.rs"],
        source_home: "theme/schema.rs",
    },
    ComponentContractEntry {
        name: "GpuiOverlayAdapterConfig",
        owner: PublicSurfaceOwnerClass::GpuiAdapterHelper,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("open_gpui_ui_components::gpui_adapter"),
        default_export: false,
        source_inputs: &["gpui_adapter"],
        source_home: "gpui_adapter",
    },
    ComponentContractEntry {
        name: "GpuiOverlayState",
        owner: PublicSurfaceOwnerClass::GpuiAdapterHelper,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("open_gpui_ui_components::gpui_adapter"),
        default_export: false,
        source_inputs: &["gpui_adapter"],
        source_home: "gpui_adapter",
    },
    ComponentContractEntry {
        name: "TextInputController",
        owner: PublicSurfaceOwnerClass::GpuiAdapterHelper,
        family: Some("form-adapter"),
        gallery_status: SurfaceGalleryStatus::AdapterOnly,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("open_gpui_ui_components::gpui_adapter"),
        default_export: false,
        source_inputs: &["gpui_adapter"],
        source_home: "gpui_adapter",
    },
    ComponentContractEntry {
        name: "init_text_input",
        owner: PublicSurfaceOwnerClass::GpuiAdapterHelper,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("open_gpui_ui_components::gpui_adapter"),
        default_export: false,
        source_inputs: &["gpui_adapter"],
        source_home: "gpui_adapter",
    },
    ComponentContractEntry {
        name: "focus_ring_shadow_with_theme",
        owner: PublicSurfaceOwnerClass::GpuiAdapterHelper,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("open_gpui_ui_components::gpui_adapter"),
        default_export: false,
        source_inputs: &["gpui_adapter"],
        source_home: "gpui_adapter",
    },
    ComponentContractEntry {
        name: "gpui_px_from_ui",
        owner: PublicSurfaceOwnerClass::GpuiAdapterHelper,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("open_gpui_ui_components::gpui_adapter"),
        default_export: false,
        source_inputs: &["gpui_adapter"],
        source_home: "gpui_adapter",
    },
    ComponentContractEntry {
        name: "gpui_point_from_ui",
        owner: PublicSurfaceOwnerClass::GpuiAdapterHelper,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("open_gpui_ui_components::gpui_adapter"),
        default_export: false,
        source_inputs: &["gpui_adapter"],
        source_home: "gpui_adapter",
    },
    ComponentContractEntry {
        name: "gpui_size_from_ui",
        owner: PublicSurfaceOwnerClass::GpuiAdapterHelper,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("open_gpui_ui_components::gpui_adapter"),
        default_export: false,
        source_inputs: &["gpui_adapter"],
        source_home: "gpui_adapter",
    },
    ComponentContractEntry {
        name: "TableBehaviorSnapshot",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("TableBehaviorSnapshot"),
        default_export: true,
        source_inputs: &[
            "table/behavior/mod.rs",
            "table/behavior/counts.rs",
            "table/behavior/columns.rs",
            "table/behavior/header.rs",
            "table/behavior/rows.rs",
            "table/behavior/tree.rs",
        ],
        source_home: "table/behavior/mod.rs",
    },
    ComponentContractEntry {
        name: "TableToolbarColors",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("TableToolbarColors"),
        default_export: true,
        source_inputs: &["table/toolbar.rs"],
        source_home: "table/toolbar.rs",
    },
    ComponentContractEntry {
        name: "TreeBehaviorSnapshot",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("TreeBehaviorSnapshot"),
        default_export: true,
        source_inputs: &["tree/render_plan.rs"],
        source_home: "tree/render_plan.rs",
    },
    ComponentContractEntry {
        name: "VirtualizedListBehaviorSnapshot",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("VirtualizedListBehaviorSnapshot"),
        default_export: true,
        source_inputs: &["virtualized_list.rs"],
        source_home: "virtualized_list.rs",
    },
    ComponentContractEntry {
        name: "CommandBehaviorSnapshot",
        owner: PublicSurfaceOwnerClass::RendererNeutralStateContract,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("CommandBehaviorSnapshot"),
        default_export: true,
        source_inputs: &["command/render_plan.rs"],
        source_home: "command/render_plan.rs",
    },
    ComponentContractEntry {
        name: "ToolbarItem",
        owner: PublicSurfaceOwnerClass::InternalImplementationDetail,
        family: Some("shell"),
        gallery_status: SurfaceGalleryStatus::InternalAnatomy,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ToolbarItem"),
        default_export: true,
        source_inputs: &["toolbar.rs"],
        source_home: "toolbar.rs",
    },
    ComponentContractEntry {
        name: "SidebarItem",
        owner: PublicSurfaceOwnerClass::InternalImplementationDetail,
        family: Some("shell"),
        gallery_status: SurfaceGalleryStatus::InternalAnatomy,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("SidebarItem"),
        default_export: true,
        source_inputs: &["sidebar.rs"],
        source_home: "sidebar.rs",
    },
    ComponentContractEntry {
        name: "ListboxOption",
        owner: PublicSurfaceOwnerClass::InternalImplementationDetail,
        family: Some("choice"),
        gallery_status: SurfaceGalleryStatus::InternalAnatomy,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ListboxOption"),
        default_export: true,
        source_inputs: &["listbox.rs"],
        source_home: "listbox.rs",
    },
    ComponentContractEntry {
        name: "primitives::active_descendant",
        owner: PublicSurfaceOwnerClass::DeprecatedRemovalTarget,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::Verification,
        docs_token: Some("primitives::active_descendant"),
        default_export: false,
        source_inputs: &["removed"],
        source_home: "removed",
    },
    ComponentContractEntry {
        name: "primitives::collection",
        owner: PublicSurfaceOwnerClass::DeprecatedRemovalTarget,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::Verification,
        docs_token: Some("primitives::collection"),
        default_export: false,
        source_inputs: &["removed"],
        source_home: "removed",
    },
    ComponentContractEntry {
        name: "primitives::controllable_state",
        owner: PublicSurfaceOwnerClass::DeprecatedRemovalTarget,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::Verification,
        docs_token: Some("primitives::controllable_state"),
        default_export: false,
        source_inputs: &["removed"],
        source_home: "removed",
    },
    ComponentContractEntry {
        name: "primitives::overlay",
        owner: PublicSurfaceOwnerClass::DeprecatedRemovalTarget,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::Verification,
        docs_token: Some("primitives::overlay"),
        default_export: false,
        source_inputs: &["removed"],
        source_home: "removed",
    },
    ComponentContractEntry {
        name: "primitives::field_state",
        owner: PublicSurfaceOwnerClass::InternalImplementationDetail,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ui_components::primitives"),
        default_export: false,
        source_inputs: &["primitives/field_state.rs"],
        source_home: "primitives/field_state.rs",
    },
    ComponentContractEntry {
        name: "primitives::focus_ring",
        owner: PublicSurfaceOwnerClass::InternalImplementationDetail,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ui_components::primitives"),
        default_export: false,
        source_inputs: &["primitives/focus_ring.rs"],
        source_home: "primitives/focus_ring.rs",
    },
    ComponentContractEntry {
        name: "primitives::roving_focus_group",
        owner: PublicSurfaceOwnerClass::InternalImplementationDetail,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ui_components::primitives"),
        default_export: false,
        source_inputs: &["primitives/roving_focus_group.rs"],
        source_home: "primitives/roving_focus_group.rs",
    },
    ComponentContractEntry {
        name: "primitives::trigger_a11y",
        owner: PublicSurfaceOwnerClass::GpuiAdapterHelper,
        family: None,
        gallery_status: SurfaceGalleryStatus::NotInGallery,
        docs_status: SurfaceDocsStatus::ComponentContract,
        docs_token: Some("ui_components::primitives"),
        default_export: false,
        source_inputs: &["primitives/trigger_a11y.rs"],
        source_home: "primitives/trigger_a11y.rs",
    },
];
