[package]
name = "open-gpui-refineable"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
description = "Refinement types used by Open GPUI."

[lints]
workspace = true

[lib]
path = "src/refineable.rs"
doctest = false

[dependencies]
open_gpui_refineable_derive.workspace = true
