[workspace]

[package]
name = "smoke_web"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "smoke_web"
path = "main.rs"

[dependencies]
js-sys = "0.3.103"
open_gpui_docking = { package = "open-gpui-docking", path = "../../../gpui_docking" }
open_gpui = { package = "open-gpui", path = "../../../gpui", default-features = false }
open_gpui_platform = { package = "open-gpui-platform", path = "../../../gpui_platform" }
wasm-bindgen = "0.2.126"
web-sys = { version = "0.3.103", features = ["Document", "DomStringMap", "Element", "HtmlElement", "Window"] }
