[package]
name = "open-gpui-reqwest-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
description = "Reqwest-backed HTTP client for Open GPUI."

[lints]
workspace = true

[features]
test-support = []

[lib]
path = "src/reqwest_client.rs"
doctest = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
futures.workspace = true
open_gpui_http_client.workspace = true
serde.workspace = true
log.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
regex.workspace = true
reqwest.workspace = true
open_gpui_core_util.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
open_gpui_http_client_tls.workspace = true

[dev-dependencies]
