#[test]
fn component_contract_docs_match_current_public_surface_vocabulary() {
    let contract = include_str!("../../../../docs/ui/component-contract.md");

    for required in [
        "components::catalog::COMPONENT_CATALOG",
        "open_gpui_ui_components::component_contract",
        "component_contract/rows/catalog.rs",
        "component_contract/projections.rs",
        "ComponentContractMetadata",
        "PublicApiExport",
        "*.scenarios.toml",
        "components/catalog.rs",
        "components/render.rs",
        "components/samples/",
        "components/runtime/",
        "components/render/",
        "`adapter-only`",
        "`internal-anatomy`",
        "`state-contract`",
        "`TableBehaviorSnapshot`",
        "not component facades",
        "default application",
        "state API",
        "`ThemeRegistry` owns built-in and user-loaded definitions",
        "`ThemeScope::new` requires a stable `ElementId`",
        "`Window::use_window_state` owns each window's",
        "`Tooltip::scoped(context, builder)`",
        "no independent non-theme immutable-stack consumer",
        "`RevealTargetHandle`",
        "`Window::bring_into_view`",
        "`DeferredBringIntoViewGuard`",
        "`VirtualizedList::bring_key_into_view`",
        "`VirtualizedListMaterializationResult`",
        "`ScrollHandle::direct_scroll_revision`",
        "latest window focus revision",
        "focus_ring_shadow_with_theme",
        "open_gpui_ui_core::grid_viewport::RowWindow",
        "open_gpui_ui_core::overlay::resolve_overlay_placement",
        "open_gpui_command::CommandDescriptor",
        "component_story_contracts_for_focus(mode)",
        "`open_gpui_ui_components::choice`",
        "`open_gpui_ui_components::gpui_adapter`",
        "public_api/default.rs",
        "official_components_match_typed_public_exports",
        "gallery_contract_metadata_matches_component_rows",
        "`ContextMenu`, and `Tree` follow that shape",
        "`menu/runtime.rs` owns submenu hover timing",
        "`table/behavior/mod.rs`",
        "`table/behavior/counts.rs`",
        "`table/behavior/columns.rs`",
        "`table/behavior/header.rs`",
        "`table/behavior/rows.rs`",
        "`table/behavior/tree.rs`",
        "must not use wildcard facade exports such as",
        "pub use runtime::*",
        "pub use samples::*",
    ] {
        assert!(
            contract.contains(required),
            "component contract docs should mention `{required}`"
        );
    }

    for removed in [
        "`ui_components::primitives::active_descendant`",
        "`ui_components::primitives::collection`",
        "`ui_components::primitives::controllable_state`",
        "`ui_components::primitives::overlay`",
        "theme registry gap",
        "COMPONENT_CATALOG` owns the current",
        "gallery constructors for official status",
        concat!("`menu_", "runtime.rs` owns submenu hover timing"),
        "`ThemeRuntime` is the GPUI",
        "`ThemeResolver::resolve` remains",
        "ThemeResolver::current(cx)",
        "COMPONENT_API_INVENTORY",
        "component_contract/source_mapping.rs",
        "component_contract/surfaces.rs",
        "component_contract/api_inventory.rs",
        "components/conformance.rs",
        "root_and_prelude_exports_match_contract_default_surface_intent",
        "command_component_source_mapping_tracks_split_owners",
        "components_catalog_consumes_component_contract_rows",
        "`scroll_target_for_key`",
        "`scroll_target_for_key_with_snapshot`",
        "semantic scroll strategy labels",
        "estimated reveal targets",
    ] {
        assert!(
            !contract.contains(removed),
            "component contract docs should not preserve removed or stale contract `{removed}`"
        );
    }
}
